// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/marinvent/marivent",
            "email": "support@marinvent.local"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/airports/{icao}": {
            "get": {
                "description": "Returns airport details for a given ICAO code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "airports"
                ],
                "summary": "Get airport by ICAO",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ICAO airport code (e.g., KJFK, EGLL)",
                        "name": "icao",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Airport"
                        }
                    }
                }
            }
        },
        "/api/v1/chart-types": {
            "get": {
                "description": "Returns all available chart types from ctypes.dbf with codes, categories, and descriptions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charts"
                ],
                "summary": "List all chart types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ChartTypesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/charts/{icao}": {
            "get": {
                "description": "Returns all charts for a given ICAO airport. Can be filtered by type (code or name) and search query.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charts"
                ],
                "summary": "List charts for ICAO",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ICAO airport code (e.g., KJFK, EGLL)",
                        "name": "icao",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chart type - can be code (1L, AP) or name (RNAV, ILS, AIRPORT). Looks up in ctypes.dbf",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search text to filter by PROC_ID (procedure name)",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ChartList"
                        }
                    }
                }
            }
        },
        "/api/v1/charts/{icao}/export/{filename}": {
            "get": {
                "description": "Exports a specific chart to PDF format. Returns the chart as a PDF file. Post-processing is enabled by default to remove waypoint overlays; use ?no_postprocess=1 to disable.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "charts"
                ],
                "summary": "Export chart to PDF",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ICAO airport code",
                        "name": "icao",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chart filename (e.g., KJFK225)",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Set to 1 to disable post-processing (default: 0)",
                        "name": "no_postprocess",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "PDF file containing the chart",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns API health status and version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Airport": {
            "type": "object",
            "properties": {
                "airport_use": {
                    "type": "string"
                },
                "beacon": {
                    "type": "boolean"
                },
                "city": {
                    "type": "string"
                },
                "country_code": {
                    "type": "string"
                },
                "customs": {
                    "type": "string"
                },
                "fuel_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "iata": {
                    "type": "string"
                },
                "icao": {
                    "type": "string"
                },
                "jet_start_unit": {
                    "type": "boolean"
                },
                "latitude": {
                    "type": "number"
                },
                "longest_runway_ft": {
                    "type": "integer"
                },
                "longitude": {
                    "type": "number"
                },
                "magnetic_variation": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "oxygen": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "repair_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "state": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "api.ChartInfo": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "chart_type": {
                    "type": "string"
                },
                "date_eff": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "has_tcl": {
                    "type": "boolean"
                },
                "icao": {
                    "type": "string"
                },
                "proc_id": {
                    "type": "string"
                },
                "sheet_id": {
                    "type": "string"
                },
                "type_name": {
                    "type": "string"
                }
            }
        },
        "api.ChartList": {
            "description": "Response containing list of charts for an ICAO",
            "type": "object",
            "properties": {
                "charts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ChartInfo"
                    }
                },
                "icao": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.ChartType": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api.ChartTypesResponse": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ChartType"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Marinvent Chart API",
	Description:      "API for accessing and exporting Jeppesen terminal charts",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
